"""Planing-craft 2.5D seakeeping tools."""

import numpy as _np

# NumPy 2 renamed the long-standing trapz implementation to trapezoid.  Keep
# the package executable in audited legacy environments without changing the
# quadrature rule used by the hydrodynamic kernels.
if not hasattr(_np, "trapezoid"):
    _np.trapezoid = _np.trapz

from .benchmark_data import compare_reference_curve, load_reference_curve
from .config import PrescribedRunningStateConfig, RunConfig, load_config
from .geometry import (
    GeometrySource,
    HullComponent,
    MultiBodySection,
    geometry_source_audit,
    load_unified_offsets_csv,
    make_delft372_demihull_surrogate,
    make_trimaran2019_surrogate,
    multibody_sections,
)
from .equilibrium import EquilibriumState, make_prescribed_equilibrium, solve_equilibrium
from .coefficients import HydroMatrices, compute_hydro_matrices
from .forced_motion_identification import (
    FirstHarmonicFit,
    ForcedMotionColumn,
    ForcedMotionMatrices,
    assemble_forced_motion_matrices,
    extract_forced_motion_column,
    fit_periodic_harmonics,
)
from .forced_motion_validation import (
    SUN2007_COEFFICIENTS,
    ForcedMotionBenchmarkRow,
    ForcedMotionCoefficientMetric,
    ForcedMotionComparisonRow,
    Sun2007TroeschAcceptance,
    compare_sun2007_troesch,
    load_sun2007_troesch_benchmark,
    nondimensionalize_forced_motion_matrices,
)
from .regimes import LoadArbiter, LoadOwnership, RegimeObservables, RegimeReport, smoothstep
from .schema import (
    HullComponentConfig,
    HydrofoilProviderConfig,
    LiftingSurfaceConfig,
    Linear2p5DProviderConfig,
    MultihullInteractionProviderConfig,
    Nonlinear2DtProviderConfig,
    ProviderSuiteConfig,
    VesselConfig,
)
from .solver import analyze_speed, simulate_time_domain_rk4
from .longitudinal_response import (
    LongitudinalFrequencyModel,
    build_faltinsen_planing_model,
    faltinsen_head_sea_excitation,
    finite_length_strip_factors,
    frequency_time_consistency,
    simulate_regular_wave_ivp,
    solve_longitudinal_frequency_response,
    wave_amplitude_linearity,
)
from .types import (
    FrequencyDomainHydrodynamics,
    HydroLoadResult,
    LongitudinalHydrodynamicMatrices,
    ModelCapabilities,
    ValidityReport,
)
from .providers import (
    HydrofoilPlaceholderProvider,
    LinearFrequencyProvider,
    MultihullInteractionPlaceholderProvider,
    NonlinearBEM2DtProvider,
    ReducedOrderPlaning2DtProvider,
    ReducedOrderPlaningLoadProvider,
    build_legacy_2p5d_provider,
)
from .kernels.nonlinear_2dt import (
    PRESCRIBED_MOTION_CONTRACT_STATUS,
    PrescribedMotion2DtCase,
    PrescribedMotion2DtResult,
    PrescribedMotionKinematics,
    PrescribedMotionSectionSolver,
    SectionalLoadHistory,
    integrate_sectional_generalized_load,
    prescribed_motion_kinematics,
    solve_prescribed_motion_case,
)
from .section_bem import (
    section_bem_multimode_radiation_diagnostics,
    section_bem_pressure_transfer_diagnostics,
    solve_heave_radiation_pdstrip_style,
    solve_pressure_transfer,
    solve_radiation_modes,
)
from .pdstrip_external import (
    PDSTRIP_EXTERNAL_STATUS,
    PDSTRIP_SECTION_DOF_LABELS,
    PDStripGeometry,
    PDStripGeometrySection,
    PDStripSectionResultBlock,
    PDStripSectionResults,
    PDStripStationHullSectionsResult,
    parse_pdstrip_geometry,
    parse_sectionresults,
    pdstrip_section_bem_comparison_rows,
    parse_sectionresults_metadata,
    pdstrip_sectionresults_rows,
    run_pdstrip_station_hull_sections,
    write_station_hull_section_case,
    run_pdstrip_external_smoke,
    write_simple_full_v_case,
)
from .station_2p5d import (
    DOF_LABELS,
    HardChineStation,
    RigidBody6DOF,
    Station6DOFMatrices,
    StationHull,
    StationMatrices,
    PDSTRIP_EXTERNAL_SECTIONS_STATUS,
    PRESSURE_TRANSFER_FORWARD_ASSEMBLY_STATUS,
    PRESSURE_TRANSFER_PDSTRIP_STEP_ASSEMBLY_STATUS,
    HYBRID_PRESSURE_DAMPING_COUPLING_STATUS,
    STRIP_2P5D_PDSTRIP_STEP_STATUS,
    assemble_external_pdstrip_section_6dof_matrices,
    assemble_experimental_bem_6dof_matrices,
    assemble_forward_speed_2p5d_matrices,
    assemble_hybrid_forward_coupling_matrices,
    assemble_hybrid_pressure_damping_coupling_matrices,
    assemble_pressure_transfer_forward_speed_matrices,
    assemble_prototype_6dof_matrices,
    assemble_prototype_strip_matrices,
    forward_speed_coupling_variant_diagnostics,
    forward_speed_coupling_station_contribution_diagnostics,
    forward_speed_2p5d_component_diagnostics,
    forward_speed_pressure_gradient_diagnostics,
    forward_speed_pressure_transfer_diagnostics,
    load_station_offsets_csv,
    load_station_hull,
    make_sl7_surrogate_hull,
    make_wigley_iii_hull,
    prototype_wave_excitation_6dof,
    station_geometry_audit,
    section_bem_multimode_station_diagnostics,
    section_bem_pressure_transfer_station_diagnostics,
    section_bem_station_diagnostics,
    solve_station_rao_6dof,
    station_rao_frequency_sweep,
)
from .validation import (
    validate_all,
    validate_faltinsen_ch9,
    validate_goal_gap_audit,
    validate_katayama_classification,
    validate_katayama_qualitative_trends,
    validate_pdstrip_external_smoke,
    validate_reasonableness,
    validate_section_bem_numerics,
)

__all__ = [
    "RunConfig",
    "PrescribedRunningStateConfig",
    "load_config",
    "GeometrySource",
    "HullComponent",
    "MultiBodySection",
    "geometry_source_audit",
    "load_unified_offsets_csv",
    "make_delft372_demihull_surrogate",
    "make_trimaran2019_surrogate",
    "multibody_sections",
    "LoadArbiter",
    "LoadOwnership",
    "RegimeObservables",
    "RegimeReport",
    "smoothstep",
    "HullComponentConfig",
    "HydrofoilProviderConfig",
    "LiftingSurfaceConfig",
    "Linear2p5DProviderConfig",
    "MultihullInteractionProviderConfig",
    "Nonlinear2DtProviderConfig",
    "ProviderSuiteConfig",
    "VesselConfig",
    "FrequencyDomainHydrodynamics",
    "HydroLoadResult",
    "LongitudinalHydrodynamicMatrices",
    "LongitudinalFrequencyModel",
    "build_faltinsen_planing_model",
    "faltinsen_head_sea_excitation",
    "finite_length_strip_factors",
    "frequency_time_consistency",
    "simulate_regular_wave_ivp",
    "solve_longitudinal_frequency_response",
    "wave_amplitude_linearity",
    "ModelCapabilities",
    "ValidityReport",
    "HydrofoilPlaceholderProvider",
    "LinearFrequencyProvider",
    "MultihullInteractionPlaceholderProvider",
    "NonlinearBEM2DtProvider",
    "ReducedOrderPlaning2DtProvider",
    "ReducedOrderPlaningLoadProvider",
    "build_legacy_2p5d_provider",
    "load_reference_curve",
    "compare_reference_curve",
    "EquilibriumState",
    "make_prescribed_equilibrium",
    "solve_equilibrium",
    "HydroMatrices",
    "compute_hydro_matrices",
    "FirstHarmonicFit",
    "ForcedMotionColumn",
    "ForcedMotionMatrices",
    "assemble_forced_motion_matrices",
    "extract_forced_motion_column",
    "fit_periodic_harmonics",
    "SUN2007_COEFFICIENTS",
    "ForcedMotionBenchmarkRow",
    "ForcedMotionCoefficientMetric",
    "ForcedMotionComparisonRow",
    "Sun2007TroeschAcceptance",
    "compare_sun2007_troesch",
    "load_sun2007_troesch_benchmark",
    "nondimensionalize_forced_motion_matrices",
    "PRESCRIBED_MOTION_CONTRACT_STATUS",
    "PrescribedMotion2DtCase",
    "PrescribedMotion2DtResult",
    "PrescribedMotionKinematics",
    "PrescribedMotionSectionSolver",
    "SectionalLoadHistory",
    "integrate_sectional_generalized_load",
    "prescribed_motion_kinematics",
    "solve_prescribed_motion_case",
    "analyze_speed",
    "simulate_time_domain_rk4",
    "section_bem_multimode_radiation_diagnostics",
    "section_bem_pressure_transfer_diagnostics",
    "solve_heave_radiation_pdstrip_style",
    "solve_pressure_transfer",
    "solve_radiation_modes",
    "PDSTRIP_EXTERNAL_STATUS",
    "PDSTRIP_SECTION_DOF_LABELS",
    "PDStripGeometry",
    "PDStripGeometrySection",
    "PDStripSectionResultBlock",
    "PDStripSectionResults",
    "PDStripStationHullSectionsResult",
    "parse_pdstrip_geometry",
    "parse_sectionresults",
    "pdstrip_section_bem_comparison_rows",
    "parse_sectionresults_metadata",
    "pdstrip_sectionresults_rows",
    "run_pdstrip_station_hull_sections",
    "write_station_hull_section_case",
    "run_pdstrip_external_smoke",
    "write_simple_full_v_case",
    "validate_all",
    "validate_faltinsen_ch9",
    "validate_goal_gap_audit",
    "validate_katayama_classification",
    "validate_katayama_qualitative_trends",
    "validate_pdstrip_external_smoke",
    "validate_reasonableness",
    "validate_section_bem_numerics",
    "DOF_LABELS",
    "HardChineStation",
    "RigidBody6DOF",
    "Station6DOFMatrices",
    "StationHull",
    "StationMatrices",
    "PDSTRIP_EXTERNAL_SECTIONS_STATUS",
    "PRESSURE_TRANSFER_FORWARD_ASSEMBLY_STATUS",
    "PRESSURE_TRANSFER_PDSTRIP_STEP_ASSEMBLY_STATUS",
    "HYBRID_PRESSURE_DAMPING_COUPLING_STATUS",
    "STRIP_2P5D_PDSTRIP_STEP_STATUS",
    "assemble_external_pdstrip_section_6dof_matrices",
    "assemble_experimental_bem_6dof_matrices",
    "assemble_forward_speed_2p5d_matrices",
    "assemble_hybrid_forward_coupling_matrices",
    "assemble_hybrid_pressure_damping_coupling_matrices",
    "assemble_pressure_transfer_forward_speed_matrices",
    "assemble_prototype_6dof_matrices",
    "assemble_prototype_strip_matrices",
    "forward_speed_coupling_variant_diagnostics",
    "forward_speed_coupling_station_contribution_diagnostics",
    "forward_speed_2p5d_component_diagnostics",
    "forward_speed_pressure_gradient_diagnostics",
    "forward_speed_pressure_transfer_diagnostics",
    "load_station_offsets_csv",
    "load_station_hull",
    "make_sl7_surrogate_hull",
    "make_wigley_iii_hull",
    "prototype_wave_excitation_6dof",
    "station_geometry_audit",
    "section_bem_multimode_station_diagnostics",
    "section_bem_pressure_transfer_station_diagnostics",
    "section_bem_station_diagnostics",
    "solve_station_rao_6dof",
    "station_rao_frequency_sweep",
]
