#!/bin/bash

mkdir patches
cd src
$Overture/bin/rap -noplot patch_s0_yz
$Overture/bin/rap -noplot patch_s1_yz
$Overture/bin/rap -noplot patch_s2_xz
$Overture/bin/rap -noplot patch_s3_xz
$Overture/bin/rap -noplot patch_s4_yz
$Overture/bin/rap -noplot patch_s5_xy
$Overture/bin/rap -noplot patch_s6_xy
$Overture/bin/rap -noplot patch_s7_xy

